// TODO: Needs Better name
// Acts as class that stores information about this particular client, where user refers to other clients 
#pragma once
#include <vector>
#include <openssl/evp.h>
#include <mutex>
#include <unordered_map>

#include "CppInterface.h"
#include "ConfigLoader.h"

#define SHARED_SECRET_PATH "/data/sharedSecrets/"

// Forward Declorations
class IncomingHandler;
class OutgoingHandler;
class Server;

class PrimaryClient {
private:
    ID clientID;

    // List of every user known from all servers for easy acsess to shared keys when dycrypting 
    // should be generated by compiling the users of every server on load
    

    // Every server that this client is a part of
    std::unordered_map<std::string, Server*> allServers;
    


    // Specific User profile information
    std::string defaultUsername;
    
    sockaddr_in preferedRelayAdress;
    IncomingHandler* incomingHandler;
    OutgoingHandler* outgoingHandler;

    // pointer to public & private keys 
    EVP_PKEY *keyPair;

    // Static pointer to the Singleton instance
    static PrimaryClient* instancePtr;
    // Mutex to ensure thread safety
    static std::mutex mtx;
    // Private Constructor
    PrimaryClient() {}

    int init();

public:
    // Deleting the copy constructor to prevent copies
    PrimaryClient(const PrimaryClient& obj) = delete;
    ~PrimaryClient();
    static PrimaryClient* getInstance();
    EVP_PKEY* getKeyPair();

    ID* getClientID();

    RemoteUser* getUser(std::string userID);
    void loadUser(RemoteUser* user);

    int registerNewUser(ID* id);
    
    // Clean up
    SOCKTYPE socketfd;
    std::unordered_map<std::string, RemoteUser*> knownConnections;

    void addNewServer(Server *server);

    // Loads all servers
    void loadAllServers();
    // loads a server from file
    void loadServer(std::string id);
    // Makes a brand new server 
    void createNewServer(std::string id);

    Server* getServer(std::string id);

    sockaddr_in getPreferedRelay();
    OutgoingHandler* getOutgoingHandler();
};