// TODO: Needs Better name
// Acts as class that stores information about this particular client, where user refers to other clients 
#pragma once
#include <vector>
#include <openssl/evp.h>
#include <mutex>
#include <unordered_map>

#include "CppInterface.h"
#include "ConfigLoader.h"


#define SHARED_SECRET_PATH "/data/sharedSecrets/"

// Forward Declorations
class IncomingHandler;
class OutgoingHandler;
class FileHandler;

class Server;

class PrimaryClient {
private:
    std::string clientID;

    // List of every user known from all servers for easy acsess to shared keys when dycrypting 
    // should be generated by compiling the users of every server on load

    // Specific User profile information
    std::string defaultUsername;
    RemoteUser* thisUser;
    
    sockaddr_in preferedRelayAdress;
    IncomingHandler* incomingHandler;
    OutgoingHandler* outgoingHandler;

    // pointer to public & private keys 
    EVP_PKEY *keyPair;

    EVP_PKEY* ML_DSAkey;

    // Static pointer to the Singleton instance
    static PrimaryClient* instancePtr;
    // Mutex to ensure thread safety
    static std::mutex mtx;
    // Private Constructor
    PrimaryClient() {}

    int init();

public:
    // Deleting the copy constructor to prevent copies
    PrimaryClient(const PrimaryClient& obj) = delete;
    ~PrimaryClient();
    static PrimaryClient* getInstance();
    EVP_PKEY* getKeyPair();
    EVP_PKEY* getDSAkey();

    std::string* getClientID();

    RemoteUser* getUser(std::string userID);
    void loadUser(RemoteUser* user);

    int registerNewUser(std::string id);
    
    // Clean up
    SOCKTYPE socketfd;
    // Every server that this client is a part of
    std::unordered_map<std::string, Server*> allServers;
    std::unordered_map<std::string, RemoteUser*> knownConnections;
    std::unordered_set<std::string> onlineConnections;
    static void enableConnection(RemoteUser*);
    static void disableConnection(RemoteUser*);

    

    // Loads all servers
    void loadAllServers();
    // loads a server from file
    void loadServer(std::string id);
    void loadServer(Server *server);
    // Makes a brand new server 
    void createNewServer(std::string id = "");

    Server* getServer(std::string id);
    RemoteUser* getThisUser();

    sockaddr_in getPreferedRelay();
    OutgoingHandler* getOutgoingHandler();

    FileHandler* fileHandler;
};