// TODO: Needs Better name
// Acts as class that stores information about this particular client, where user refers to other clients 
#pragma once
#include "Server.h"
#include "IncomingHandler.h"
#include <vector>
#include <openssl/evp.h>
#include <mutex>
#include <unordered_map>

using namespace std;

class PrimaryClient {
private:
    UUID clientID;

    // List of every user known from all servers for easy acsess to shared keys when dycrypting 
    // should be generated by compiling the users of every server on load
    unordered_map<string, RemoteUser*> knownConnections;

    // Every server that this client is a part of
    unordered_map<string, Server> allServers;


    // Specific User profile information
    string defaultUsername;


    // pointer to public & private keys 
    EVP_PKEY *keyPair;

    // Static pointer to the Singleton instance
    static PrimaryClient* instancePtr;
    // Mutex to ensure thread safety
    static mutex mtx;
    // Private Constructor
    PrimaryClient() {}

public:
    // Deleting the copy constructor to prevent copies
    PrimaryClient(const PrimaryClient& obj) = delete;
    static PrimaryClient* getInstance();
    int registerNewUser(UUID id, unsigned char* secret);
    EVP_PKEY* getKeyPair();

    UUID getClientID();

    RemoteUser* getUser(string userID);

    // A Temparary buffer for the current ongoing handshake, TODO allow for multiple handshakes to be ongoing at once
    unsigned char handShakeRand[ML_KEM_HANDSHAKE_RANDSIZE];
};